### ISSUE TITLE
Not working in Visual Studio 2019 v16.7.2

### ISSUE THREAD

**Issue by yor-so** [stefanegli/ResxFormatter#1]
**Describe the bug**
The extension was working ok but at some point recently it stopped working. I'm keeping my VS2019 updated, using the last version v16.7.2, in windows 10. When I hit save (in the save icon or with the ctrl + s shortcut), the resource strings are not being sorted. The file is not being updated in any way. I tried in two different computers.

![Capture](https://user-images.githubusercontent.com/5457965/91492427-dffc6f80-e872-11ea-9015-76f05b7d927f.PNG)

**Comment by stefanegli** [comment]
On my machine it still seems to work, can you please check:
- Are the settings in fact correct (maybe something changed, and sorting etc.. is no longer active)?
- Can you tell me what is written to Output Window?
![image](https://user-images.githubusercontent.com/3390675/91538545-44bdd580-e918-11ea-9abe-e8bcc18e0dcf.png)

**Comment by royr719** [comment]
@stefanegli there is nothing in the output window

**Comment by stefanegli** [comment]
I see, and I guess the settings are correct... could you check if the extension is in fact enabled? I just noticed on one of my installations, that the extension was disabled. I am not sure how this happened. I certainly cannot remember disabling it myself.

**Comment by stefanegli** [comment]
@yor-so: Did you check if the extension was disabled?

**Comment by yor-so** [comment]
Yes, the extension was enabled in both computers. I haven't tested in my colleague's computer but for some reason is working now, even though before I double checked that the extension was enabled and still was not working. I don't know how to reproduce it but I'll let you know if it happens again. Thanks.

**Comment by OhSoGood** [comment]
Hi
With Visual Studio 16.9.2, I just faced the same behavior. Your extension (v1.0.29) has been working for weeks (and it's really great!!!) and suddenly I had 2 resx whose resource strings were no more sorted and the front comment also remained. Nothing in output windows, the extension was still active. I simply closed VS and reopen it... and everything work again.

Maybe you could add an option to activate logs , in order to track the issue? If that worths it ?

**Comment by stefanegli** [comment]
@OhSoGood Sorry I must have some missed your message. 

Certainly glad to hear that it works again. The extension does write logs and I cannot quite see why it would not write anything if VS invokes the necessary event (cf. OnDocumentSaved method in ResxFormatterPackage.cs). Or to put it differently: I do not see what else I can really add to make this problem visible.
