### ISSUE TITLE
resx_formatter_remove_documentation_comment should not ADD the documentation comment

### ISSUE THREAD

**Issue by Mertsch** [stefanegli/ResxFormatter#11]
**Describe the bug**
The setting `resx_formatter_remove_documentation_comment` is either named misleadingly or incorrect.

What `resx_formatter_remove_documentation_comment=true` does:
* removes **all** XML comments, not just the documentation comment

What `resx_formatter_remove_documentation_comment=false` does:
* **Adds** the documentation comment
* Keeps existing non-documentation comments.

**Expected behavior**
What `resx_formatter_remove_documentation_comment=true` should do:
* Remove **only** the documentation comment - maybe identified by `Microsoft ResX Schema` string

What `resx_formatter_remove_documentation_comment=false` should do:
* Keep existing comments the way they are.

**Desktop (please complete the following information):**
 - Version 3.1.80

**Additional context**
I think it should be totally legit to have XML comments throughout the ResX file and the extension just ignoring them.

**Comment by stefanegli** [comment]
I was considering to do this in the beginning, but there were two things that lead to the current behavior:

- It was not quite clear how I should distinguish comments (I guess it can be done, but I did not have an immediate solution).
- The format does allow for comments as part of the schema e.g.:
````  
<data name="abc" xml:space="preserve">
    <value>1</value>
    <comment>test comment</comment>
</data>
````  

I am not going to be able to do anything here in the next couple of weeks, but I am going to consider to change the behavior unless of course you would be happy enough to use the "comment" notes that the RESX format provides.

**Comment by Mertsch** [comment]
I exclusively need XML comments for ReSharper
![2023-06-24 16-33-47 devenv](https://github.com/stefanegli/ResxFormatter/assets/9402861/9cc4d469-ff5c-415f-97d0-343e0c9e04a5)
![2023-06-24 16-35-08 devenv](https://github.com/stefanegli/ResxFormatter/assets/9402861/78ff681b-983d-4a81-801e-964e3888257a)
There is no other reason.
I also use the `<comment>` feature.

If the cleanup would just leave the comments alone and **not add** them, I would already be happy 😄 

Thank you for your time and effort!

**Comment by Mertsch** [comment]
Hey Stefan, I have chosen to rethink the R# problem and configured the inspection to not show anymore. This removes the need for XML Comments and I can use your great tool 😄.

You may close the issue if you want to keep the logic as is.

BTW: Support for `.editorconfig` - sooooo nice!

**Comment by stefanegli** [comment]
:-)

Thanks for the feedback... Resharper is a good reason to look into this some more. But as mentioned before it will take some time.

**Comment by stefanegli** [comment]
I think I will not implement this for now because of the following reasons:
- Nobody seems to need this behavior
- My tests showed that the RESX Editor also removes such comments, which may have been the reason that I did not implement it in the beginning

**Comment by Mertsch** [comment]
And as said, it's not really an issue for me anymore 😄 

Thanks for your great work.
